version: '2'
services:
  mapas:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: /var/www/dev/start.sh

    ports:
      - "80:80"
    volumes:
      - ../docker-data/assets:/var/www/html/assets
      - ../docker-data/public-files:/var/www/html/files
      - ../docker-data/private-files:/var/www/var/private-files

      - ../docker/common/config.d:/var/www/config/common.d
      - ../docker/common/lgpd-terms:/var/www/config/lgpd-terms

      - ./config.d:/var/www/config/config.d

      # themes and plugins
      - ../themes/MapasPA:/var/www/src/themes/MapasPA
      - ../plugins/MapasBlame:/var/www/src/plugins/MapasBlame
      - ../plugins/MultipleLocalAuth:/var/www/src/plugins/MultipleLocalAuth
      - ../plugins/AdminLoginAsUser:/var/www/src/plugins/AdminLoginAsUser
      - ../plugins/CreateGeoDivisions:/var/www/src/plugins/CreateGeoDivisions
      - ../plugins/SettingsPa:/var/www/src/plugins/SettingsPa
      - ../plugins/SpamDetector:/var/www/src/plugins/SpamDetector
      - ../plugins/ValuersManagement:/var/www/src/plugins/ValuersManagement

    environment:
      - PENDING_PCACHE_RECREATION_INTERVAL=3
      - JOBS_INTERVAL=3
      
      - APP_MODE=development
      - REDIS_CACHE=redis
      - SESSIONS_SAVE_PATH=tcp://redis:6379
      - MAILER_TRANSPORT=smtp://mailhog:1025
      - MAILER_FROM=sysadmin@localhost

      - BUILD_ASSETS=1
      
    depends_on:
      - db
      - redis
      - mailhog

    stdin_open: true
    tty: true

  redis:
    image: redis:6
    command: --maxmemory 256Mb --maxmemory-policy allkeys-lru  

  db:
    image: postgis/postgis:14-master
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
    ports:
      - "5432:5432"
    volumes:
      - ../docker/db:/docker-entrypoint-initdb.d
      - ../docker-data/db-data:/var/lib/postgresql/data


  mailhog: 
    image: mailhog/mailhog
    ports:
      - "8025:8025"

